trigger:
- main

variables:
  vmImageName: 'ubuntu-latest'
  environmentName: 'dev'
  npm_config_cache: $(Pipeline.Workspace)/.npm
  azureSubscription: 'c513d4c9-c82c-4c3a-a9e4-2b60e1b673af'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - task: Cache@2
      inputs:
        key: 'npm | "$(Agent.OS)" | package-lock.json'
        restoreKeys: |
          npm | "$(Agent.OS)"
        path: $(npm_config_cache)
      displayName: 'Cache npm'

    - script: npm ci
      displayName: 'Install and remove cached node_modules'

    - task: Cache@2
      inputs:
        key: next | "$(Agent.OS)" | package-lock.json
        path: '$(System.DefaultWorkingDirectory)/.next/cache'
      displayName: 'Cache .next/cache'

    - script: npm run build
      displayName: 'Build'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
        verbose: true
        excludeFiles: |
          **/.git/**
          **/.github/**
          **/.vscode/**

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        ArtifactName: 'drop'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
    
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureAppServiceSettings@1
            inputs:
              azureSubscription: $(azureSubscription)
              appName: 'flickidFE'
              appSettings: |
                [
                  { "name": "PORT", "value": "8080", "slotSetting": false },
                  { "name": "SCM_DO_BUILD_DURING_DEPLOYMENT", "value": "false", "slotSetting": false },
                  { "name": "WEBSITE_NODE_DEFAULT_VERSION", "value": "20.x", "slotSetting": false },
                  { "name": "ENABLE_ORYX_BUILD", "value": "false", "slotSetting": false },
                  { "name": "WEBSITE_NPM_DEFAULT_VERSION", "value": "9.x", "slotSetting": false },
                  { "name": "WEBSITES_CONTAINER_START_TIME_LIMIT", "value": "1800", "slotSetting": false }
                ]

          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              destinationFolder: '$(Pipeline.Workspace)/drop-extracted'
              cleanDestinationFolder: true

          - task: AzureWebApp@1
            inputs:
              azureSubscription: $(azureSubscription)
              appType: 'webApp'
              appName: 'flickidFE'
              package: '$(Pipeline.Workspace)/drop-extracted/.next/standalone'
